# Generated by Django 5.2.11 on 2026-04-15 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_grocerylist_store_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('variant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='api.product')),
            ],
            options={
                'verbose_name': 'Product Barcode',
                'verbose_name_plural': 'Product Barcodes',
                'ordering': ['-added_at'],
            },
        ),
    ]
