# Generated by Django 5.2.11 on 2026-04-18 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productbarcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groceryitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='store',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.store'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='groceryitem',
            unique_together={('grocery_list', 'product', 'store')},
        ),
    ]
