# Generated by Django 5.2.11 on 2026-02-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
