# Generated by Django 5.2.11 on 2026-02-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_store_latitude_store_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='store',
            name='longitude',
        ),
    ]
